#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lj586492
    url: jdbc:mysql://119.23.205.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true  #打印sql语句
    jackson:
      default-property-inclusion: non_null #字段为null,数据不返回前端
server:
  servlet:
    context-path: /sell

wechat: #微信公众号
  mpAppId: wxd898fcb01713c658
  mpAppSecret: 29d8a650db31472aa87800e3b0d739f2
  mchId: 1409146202
  mchKey: c976503d34ca432c601361f969fd8d85
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://lijing.nat300.top/sell/pay/notify

