#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Lj586492
    url: jdbc:mysql://119.23.205.106/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true  #打印sql语句
server:
  servlet:
    context-path: /sell

